dist: xenial
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - coverage run --source app/tests/ -m pytest
#need to tell Travis-CI to run the coveralls command after the test ran successfully.
after_success:
  - coveralls
