
language: python

python:
  - "3.6"
  
virtualenv:
    system_site_packages: true

install:
  - pip install -r requirements.txt
  - pip install coveralls


script:
  - pytest --cov=app tests/

after_success:
  - coveralls