
language: python
python:
- "3.6"
- "3.6-dev"
- "3.7-dev"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt
  
# command to run tests

script:
  - pytest --cov=app
#need to tell Travis-CI to run the coveralls command after the test ran successfully.
after_success:
  - coveralls
